"""Bundled standard API list-price snapshot dated 2026-09-11.

All numeric strings are USD per one million tokens.  This module is kept as
plain immutable data so updating prices is an explicit, reviewable operation;
QuotaDeck never treats a web scrape as a billing source at runtime.

The OpenAI and xAI rows use their standard *short-context* rates.  Anthropic
retains separate 5-minute and 1-hour prompt-cache write rates.  Cursor rows are
only the model-token rates published by Cursor and deliberately exclude any
Cursor Token Rate, cursorTokenFee, taxes, credits, or other account charges.
"""

from __future__ import annotations


PRICE_CATALOG_DATE = "2026-09-11"
PRICE_CATALOG_VERSION = "2026-09-11.2"
PRICE_UNIT_TOKENS = 1_000_000

PRICE_SOURCE_URLS: dict[str, str] = {
    "codex": "https://developers.openai.com/api/docs/pricing",
    "claude": "https://platform.claude.com/docs/en/about-claude/pricing",
    "cursor": "https://cursor.com/docs/models-and-pricing",
    "grok": "https://docs.x.ai/developers/pricing",
}


# Fields:
#   provider, model, aliases, input, cached_input, cache_write,
#   cache_write_5m, cache_write_1h, output, price_scope, base_model_only
# Missing cache prices are represented by None, never silently inferred.
CATALOG_ROWS: tuple[dict[str, object], ...] = (
    # OpenAI standard processing, short-context prices.
    {
        "provider": "codex",
        "model": "gpt-6-astra",
        "aliases": ("GPT-6 Astra", "astra"),
        "input": "10",
        "cached_input": "1",
        "cache_write": "12.5",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "50",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "codex",
        "model": "gpt-5.6-sol",
        "aliases": ("GPT-5.6 Sol", "sol"),
        "input": "4",
        "cached_input": "0.4",
        "cache_write": "5",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "20",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "codex",
        "model": "gpt-5.6-terra",
        "aliases": ("GPT-5.6 Terra", "terra"),
        "input": "2",
        "cached_input": "0.2",
        "cache_write": "2.5",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "12",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "codex",
        "model": "gpt-5.6-luna",
        "aliases": ("GPT-5.6 Luna", "luna"),
        "input": "0.2",
        "cached_input": "0.02",
        "cache_write": "0.25",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "1.2",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },

    # Anthropic first-party Claude API prices.
    {
        "provider": "claude",
        "model": "claude-fable-5-1",
        "aliases": ("Claude Fable 5.1", "claude-fable-5.1", "fable-5.1"),
        "input": "10",
        "cached_input": "0.25",
        "cache_write": None,
        "cache_write_5m": "12.5",
        "cache_write_1h": "20",
        "output": "50",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-mythos-5-1",
        "aliases": ("Claude Mythos 5.1", "claude-mythos-5.1", "mythos-5.1"),
        "input": "10",
        "cached_input": "0.25",
        "cache_write": None,
        "cache_write_5m": "12.5",
        "cache_write_1h": "20",
        "output": "50",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-fable-5",
        "aliases": ("Claude Fable 5", "fable-5"),
        "input": "10",
        "cached_input": "1",
        "cache_write": None,
        "cache_write_5m": "12.5",
        "cache_write_1h": "20",
        "output": "50",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-mythos-5",
        "aliases": ("Claude Mythos 5", "mythos-5"),
        "input": "10",
        "cached_input": "1",
        "cache_write": None,
        "cache_write_5m": "12.5",
        "cache_write_1h": "20",
        "output": "50",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-opus-5",
        "aliases": ("Claude Opus 5", "opus-5"),
        "input": "5",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": "6.25",
        "cache_write_1h": "10",
        "output": "25",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-opus-4-8",
        "aliases": ("Claude Opus 4.8", "claude-opus-4.8", "opus-4.8"),
        "input": "5",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": "6.25",
        "cache_write_1h": "10",
        "output": "25",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-opus-4-7",
        "aliases": ("Claude Opus 4.7", "claude-opus-4.7", "opus-4.7"),
        "input": "5",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": "6.25",
        "cache_write_1h": "10",
        "output": "25",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-opus-4-6",
        "aliases": ("Claude Opus 4.6", "claude-opus-4.6", "opus-4.6"),
        "input": "5",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": "6.25",
        "cache_write_1h": "10",
        "output": "25",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-opus-4-5",
        "aliases": ("Claude Opus 4.5", "claude-opus-4.5", "opus-4.5"),
        "input": "5",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": "6.25",
        "cache_write_1h": "10",
        "output": "25",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-opus-4-1",
        "aliases": ("Claude Opus 4.1", "claude-opus-4.1", "opus-4.1"),
        "input": "15",
        "cached_input": "1.5",
        "cache_write": None,
        "cache_write_5m": "18.75",
        "cache_write_1h": "30",
        "output": "75",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-opus-4",
        "aliases": ("Claude Opus 4", "opus-4"),
        "input": "15",
        "cached_input": "1.5",
        "cache_write": None,
        "cache_write_5m": "18.75",
        "cache_write_1h": "30",
        "output": "75",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-sonnet-5",
        "aliases": ("Claude Sonnet 5", "sonnet-5"),
        "input": "2",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": "2.5",
        "cache_write_1h": "4",
        "output": "10",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-sonnet-4-6",
        "aliases": ("Claude Sonnet 4.6", "claude-sonnet-4.6", "sonnet-4.6"),
        "input": "3",
        "cached_input": "0.3",
        "cache_write": None,
        "cache_write_5m": "3.75",
        "cache_write_1h": "6",
        "output": "15",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-sonnet-4-5",
        "aliases": (
            "Claude Sonnet 4.5",
            "claude-sonnet-4.5",
            "claude-sonnet-4-5-20250929",
            "sonnet-4.5",
        ),
        "input": "3",
        "cached_input": "0.3",
        "cache_write": None,
        "cache_write_5m": "3.75",
        "cache_write_1h": "6",
        "output": "15",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-sonnet-4",
        "aliases": (
            "Claude Sonnet 4",
            "claude-sonnet-4-20250514",
            "sonnet-4",
        ),
        "input": "3",
        "cached_input": "0.3",
        "cache_write": None,
        "cache_write_5m": "3.75",
        "cache_write_1h": "6",
        "output": "15",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-haiku-4-5-20251001",
        "aliases": (
            "Claude Haiku 4.5",
            "claude-haiku-4-5",
            "claude-haiku-4.5",
            "haiku-4.5",
        ),
        "input": "1",
        "cached_input": "0.1",
        "cache_write": None,
        "cache_write_5m": "1.25",
        "cache_write_1h": "2",
        "output": "5",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },
    {
        "provider": "claude",
        "model": "claude-3-5-haiku-20241022",
        "aliases": ("Claude Haiku 3.5", "claude-haiku-3.5", "haiku-3.5"),
        "input": "0.8",
        "cached_input": "0.08",
        "cache_write": None,
        "cache_write_5m": "1",
        "cache_write_1h": "1.6",
        "output": "4",
        "price_scope": "first_party_standard",
        "base_model_only": False,
    },

    # Cursor-published model rates.  These are not the complete Cursor bill.
    {
        "provider": "cursor",
        "model": "grok-4.6",
        "aliases": ("Cursor Grok 4.6", "Grok 4.6"),
        "input": "2",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "6",
        "price_scope": "cursor_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "grok-4.6-fast",
        "aliases": ("Cursor Grok 4.6 Fast", "Grok 4.6 (Fast)"),
        "input": "4",
        "cached_input": "1",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "12",
        "price_scope": "cursor_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "grok-4.5",
        "aliases": ("Cursor Grok 4.5", "Grok 4.5"),
        "input": "2",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "6",
        "price_scope": "cursor_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "grok-4.5-fast",
        "aliases": ("Cursor Grok 4.5 Fast", "Grok 4.5 (Fast)"),
        "input": "4",
        "cached_input": "1",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "18",
        "price_scope": "cursor_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "composer-2.5",
        "aliases": ("Composer 2.5",),
        "input": "0.5",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "2.5",
        "price_scope": "cursor_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "composer-2.5-fast",
        "aliases": ("Composer 2.5 Fast", "Composer 2.5 (Fast)"),
        "input": "3",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "15",
        "price_scope": "cursor_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "claude-fable-5-1",
        "aliases": ("Claude Fable 5.1",),
        "input": "10",
        "cached_input": "0.25",
        "cache_write": "12.5",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "50",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "claude-opus-5",
        "aliases": ("Claude Opus 5",),
        "input": "5",
        "cached_input": "0.5",
        "cache_write": "6.25",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "25",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "claude-sonnet-5",
        "aliases": ("Claude Sonnet 5",),
        "input": "2",
        "cached_input": "0.2",
        "cache_write": "2.5",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "10",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "gemini-3.1-pro",
        "aliases": ("Gemini 3.1 Pro",),
        "input": "2",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "12",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "gemini-3.8-flash",
        "aliases": ("Gemini 3.8 Flash",),
        "input": "0.75",
        "cached_input": "0.075",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "3.5",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "gpt-5.6-luna",
        "aliases": ("GPT-5.6 Luna",),
        "input": "0.2",
        "cached_input": "0.02",
        "cache_write": "0.25",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "1.2",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "gpt-5.6-sol",
        "aliases": ("GPT-5.6 Sol",),
        "input": "4",
        "cached_input": "0.4",
        "cache_write": "5",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "20",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "gpt-5.6-terra",
        "aliases": ("GPT-5.6 Terra",),
        "input": "2",
        "cached_input": "0.2",
        "cache_write": "2.5",
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "12",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },
    {
        "provider": "cursor",
        "model": "muse-spark-1.3",
        "aliases": ("Muse Spark 1.3",),
        "input": "1.25",
        "cached_input": "0.15",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "4.25",
        "price_scope": "cursor_other_model_rate",
        "base_model_only": True,
    },

    # xAI standard short-context text API prices.
    {
        "provider": "grok",
        "model": "grok-4.6",
        "aliases": ("Grok 4.6",),
        "input": "2",
        "cached_input": "0.5",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "6",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "grok",
        "model": "grok-build-0.1",
        "aliases": ("Grok Build 0.1", "grok-build"),
        "input": "1",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "2",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "grok",
        "model": "grok-4.5",
        "aliases": ("Grok 4.5",),
        "input": "2",
        "cached_input": "0.3",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "6",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "grok",
        "model": "grok-4.3",
        "aliases": ("Grok 4.3",),
        "input": "1.25",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "2.5",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "grok",
        "model": "grok-4.20-multi-agent-0309",
        "aliases": ("Grok 4.20 Multi Agent 0309",),
        "input": "1.25",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "2.5",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "grok",
        "model": "grok-4.20-0309-reasoning",
        "aliases": ("Grok 4.20 0309 Reasoning",),
        "input": "1.25",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "2.5",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
    {
        "provider": "grok",
        "model": "grok-4.20-0309-non-reasoning",
        "aliases": ("Grok 4.20 0309 Non Reasoning",),
        "input": "1.25",
        "cached_input": "0.2",
        "cache_write": None,
        "cache_write_5m": None,
        "cache_write_1h": None,
        "output": "2.5",
        "price_scope": "standard_short_context",
        "base_model_only": False,
    },
)
